backbone_type: resnet
comment: RandomMask_49_backbone_type_resnet_planes_multipliers_2_2_2_sim_coeff_6.25_std_coeff_50.0_lr_0.3
planes_multipliers:
- 2
- 2
- 2
sim_coeff: 6.25
start_lr: 0.3
std_coeff: 50.0
