backbone_type: resnet
comment: RandomMask_61_backbone_type_resnet_planes_multipliers_2_2_2_sim_coeff_12.5_std_coeff_6.25_lr_0.15
planes_multipliers:
- 2
- 2
- 2
sim_coeff: 12.5
start_lr: 0.15
std_coeff: 6.25
