backbone_type: convnext
comment: RandomMask_314_backbone_type_convnext_planes_multipliers_2_4_2_sim_coeff_12.5_std_coeff_6.25_lr_2.4
planes_multipliers:
- 2
- 4
- 2
sim_coeff: 12.5
start_lr: 2.4
std_coeff: 6.25
