backbone_type: convnext
comment: RandomMask_340_backbone_type_convnext_planes_multipliers_2_2_2_sim_coeff_12.5_std_coeff_25.0_lr_1.2
planes_multipliers:
- 2
- 2
- 2
sim_coeff: 12.5
start_lr: 1.2
std_coeff: 25.0
