backbone_type: resnet
comment: RandomMask_512_backbone_type_resnet_planes_multipliers_2_8_2_sim_coeff_12.5_std_coeff_12.5_lr_1.2
planes_multipliers:
- 2
- 8
- 2
sim_coeff: 12.5
start_lr: 1.2
std_coeff: 12.5
