backbone_type: resnet
comment: RandomMask_165_backbone_type_resnet_planes_multipliers_2_8_2_sim_coeff_25.0_std_coeff_25.0_lr_2.4
planes_multipliers:
- 2
- 8
- 2
sim_coeff: 25.0
start_lr: 2.4
std_coeff: 25.0
