backbone_type: convnext
comment: RandomMask_256_backbone_type_convnext_planes_multipliers_2_2_2_sim_coeff_6.25_std_coeff_12.5_lr_0.15
planes_multipliers:
- 2
- 2
- 2
sim_coeff: 6.25
start_lr: 0.15
std_coeff: 12.5
