backbone_type: resnet
comment: RandomMask_629_backbone_type_resnet_planes_multipliers_2_8_2_sim_coeff_50.0_std_coeff_50.0_lr_0.6
planes_multipliers:
- 2
- 8
- 2
sim_coeff: 50.0
start_lr: 0.6
std_coeff: 50.0
