backbone_type: resnet
comment: RandomMask_594_backbone_type_resnet_planes_multipliers_2_2_2_sim_coeff_50.0_std_coeff_12.5_lr_0.3
planes_multipliers:
- 2
- 2
- 2
sim_coeff: 50.0
start_lr: 0.3
std_coeff: 12.5
