backbone_type: convnext
comment: RandomMask_247_backbone_type_convnext_planes_multipliers_2_2_2_sim_coeff_6.25_std_coeff_6.25_lr_0.6
planes_multipliers:
- 2
- 2
- 2
sim_coeff: 6.25
start_lr: 0.6
std_coeff: 6.25
