backbone_type: convnext
comment: RandomMask_459_backbone_type_convnext_planes_multipliers_2_8_2_sim_coeff_50.0_std_coeff_25.0_lr_0.6
planes_multipliers:
- 2
- 8
- 2
sim_coeff: 50.0
start_lr: 0.6
std_coeff: 25.0
