backbone_type: convnext
comment: RandomMask_420_backbone_type_convnext_planes_multipliers_2_8_2_sim_coeff_25.0_std_coeff_50.0_lr_2.4
planes_multipliers:
- 2
- 8
- 2
sim_coeff: 25.0
start_lr: 2.4
std_coeff: 50.0
