backbone_type: resnet
comment: RandomMask_9_backbone_type_resnet_planes_multipliers_2_8_2_sim_coeff_6.25_std_coeff_6.25_lr_0.6
planes_multipliers:
- 2
- 8
- 2
sim_coeff: 6.25
start_lr: 0.6
std_coeff: 6.25
