backbone_type: convnext
comment: RandomMask_287_backbone_type_convnext_planes_multipliers_2_4_2_sim_coeff_6.25_std_coeff_50.0_lr_0.15
planes_multipliers:
- 2
- 4
- 2
sim_coeff: 6.25
start_lr: 0.15
std_coeff: 50.0
