backbone_type: resnet
comment: RandomMask_622_backbone_type_resnet_planes_multipliers_2_4_2_sim_coeff_50.0_std_coeff_50.0_lr_0.15
planes_multipliers:
- 2
- 4
- 2
sim_coeff: 50.0
start_lr: 0.15
std_coeff: 50.0
