backbone_type: resnet
comment: RandomMask_155_backbone_type_resnet_planes_multipliers_2_4_2_sim_coeff_25.0_std_coeff_25.0_lr_0.3
planes_multipliers:
- 2
- 4
- 2
sim_coeff: 25.0
start_lr: 0.3
std_coeff: 25.0
