backbone_type: convnext
comment: RandomMask_283_backbone_type_convnext_planes_multipliers_2_2_2_sim_coeff_6.25_std_coeff_25.0_lr_2.4
planes_multipliers:
- 2
- 2
- 2
sim_coeff: 6.25
start_lr: 2.4
std_coeff: 25.0
