backbone_type: convnext
comment: RandomMask_304_backbone_type_convnext_planes_multipliers_2_2_2_sim_coeff_12.5_std_coeff_6.25_lr_0.3
planes_multipliers:
- 2
- 2
- 2
sim_coeff: 12.5
start_lr: 0.3
std_coeff: 6.25
