backbone_type: convnext
comment: RandomMask_353_backbone_type_convnext_planes_multipliers_2_4_2_sim_coeff_12.5_std_coeff_50.0_lr_0.6
planes_multipliers:
- 2
- 4
- 2
sim_coeff: 12.5
start_lr: 0.6
std_coeff: 50.0
