backbone_type: convnext
comment: RandomMask_392_backbone_type_convnext_planes_multipliers_2_4_2_sim_coeff_25.0_std_coeff_25.0_lr_0.15
planes_multipliers:
- 2
- 4
- 2
sim_coeff: 25.0
start_lr: 0.15
std_coeff: 25.0
