backbone_type: convnext
comment: RandomMask_423_backbone_type_convnext_planes_multipliers_2_8_2_sim_coeff_50.0_std_coeff_6.25_lr_0.15
planes_multipliers:
- 2
- 8
- 2
sim_coeff: 50.0
start_lr: 0.15
std_coeff: 6.25
