backbone_type: convnext
comment: RandomMask_251_backbone_type_convnext_planes_multipliers_2_4_2_sim_coeff_6.25_std_coeff_6.25_lr_1.2
planes_multipliers:
- 2
- 4
- 2
sim_coeff: 6.25
start_lr: 1.2
std_coeff: 6.25
