backbone_type: convnext
comment: RandomMask_356_backbone_type_convnext_planes_multipliers_2_4_2_sim_coeff_12.5_std_coeff_50.0_lr_1.2
planes_multipliers:
- 2
- 4
- 2
sim_coeff: 12.5
start_lr: 1.2
std_coeff: 50.0
