backbone_type: resnet
comment: RandomMask_543_backbone_type_resnet_planes_multipliers_2_2_2_sim_coeff_12.5_std_coeff_50.0_lr_2.4
planes_multipliers:
- 2
- 2
- 2
sim_coeff: 12.5
start_lr: 2.4
std_coeff: 50.0
