backbone_type: resnet
comment: RandomMask_2_backbone_type_resnet_planes_multipliers_2_4_2_sim_coeff_6.25_std_coeff_6.25_lr_0.15
planes_multipliers:
- 2
- 4
- 2
sim_coeff: 6.25
start_lr: 0.15
std_coeff: 6.25
